name: 'Puppeteer Headful with Commands'
author: Mau Frontier (forked from an action by Jacob Lowe)
description: 'Github Action that allows for Puppeteer to be run in headful mode, passing complex bash commands'
branding:
  icon: 'monitor' 
  color: 'purple'
inputs:
  commands:
    description: 'Commands'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.commands }}