name: 'Puppeteer Headful with Commands'
description: 'Github Action that allows for Puppeteer to be run in "headful" mode (not headless).'
inputs:
  commands:
    description: 'Commands'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.commands }}